### ISSUE TITLE
Missing newline stops config from being used

### ISSUE THREAD

**Issue by doncornelius01** [aws-samples/ec2-spot-for-folding-at-home#2]
https://github.com/aws-samples/ec2-spot-for-folding-at-home/blob/9aa58a3bb4701274205e4b1df95c8c8524cc52a7/fah-ec2-spot.yaml#L529

For some reason, the newline is missing and stops the user config from being copied.  Adding a newline at the end of line 529 fixes the issue

**Comment by doncornelius01** [comment]
Looks like line 549 needs a newline at the end as well?  Testing now
https://github.com/aws-samples/ec2-spot-for-folding-at-home/blob/9aa58a3bb4701274205e4b1df95c8c8524cc52a7/fah-ec2-spot.yaml#L549

I test by launching the template, then using Session Manager to log in and view `/var/lib/cloud/instance/scripts/part-001`

**Comment by horsfieldsa** [comment]
Fix pending peer review.
